created_at: '2025-07-12T16:46:21.837149'
tokens:
  github_hardikSrivastav:
    access_token: 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
    created_at: '2025-07-12T16:51:45.706634'
    is_valid: true
    last_used: '2025-07-12T16:52:48.886207'
    provider: github
    scope: repo,user:email
    token_type: bearer
    user_identifier: hardikSrivastav
    user_info:
      avatar_url: https://avatars.githubusercontent.com/u/69335300?v=4
      email: null
      id: 69335300
      login: hardikSrivastav
      name: Hardik Srivastava
      private_repos: null
      public_repos: 21
updated_at: '2025-07-12T16:51:45.706654'
version: '1.0'
