version: '3.8'

services:
  rag-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8792:8792"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///./data/rag_system.db
    depends_on:
      - qdrant
    networks:
      - rag-network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6338:6333"  # Using port 6338 (6333 + 5) as per your convention
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - rag-network
    restart: unless-stopped

networks:
  rag-network:
    driver: bridge

volumes:
  qdrant_data:
  uploads:
  logs: 